In [1]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a[:2, 1:3]

In [2]:
a[0, 1]

2

In [3]:
b[0, 0] = 77

77

In [5]:
a[a > 5]

array([77,  6,  7,  8,  9, 10, 11, 12])

In [16]:
a = np.random.randn(3, 5)

In [17]:
a

array([[-0.19536701,  0.54302451, -0.34799806, -0.43426046, -0.51889133],
       [ 1.04384763,  0.33155451,  0.90259703, -1.71794796,  1.02614056],
       [-0.62367695, -0.9126529 , -1.56216535, -1.04854933,  2.03289233]])

In [11]:
a.sum(axis=1)

array([-2.32426261, -0.30188893,  2.68620021])

In [23]:
a[range(2), [2, 3]].sum(keepdims = True).shape

(1,)

In [24]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [27]:
x.shape, w.shape, b.shape

((2, 4, 5, 6), (120, 3), (3,))

In [28]:
np.prod(input_shape)

120

In [32]:
np.linspace(0.1, 0.5, num=5)

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [33]:
i = 2

In [37]:
'W%s' % (i+2)

'W4'