In [2]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b = a[:2, 1:3]

In [2]:
a[0, 1]

2

In [3]:
b[0, 0] = 77

77

In [5]:
a[a > 5]

array([77,  6,  7,  8,  9, 10, 11, 12])

In [5]:
a = np.random.randn(3, 5)

In [6]:
a

array([[-1.28626036,  0.10563982, -0.86851349,  1.5185012 , -1.16145324],
       [ 0.5788466 ,  0.78844707,  2.03261402,  1.07951283,  0.08620047],
       [-1.19976509,  0.01383939,  1.79341946,  1.29916684, -1.53395767]])

In [9]:
a.max(axis=1,keepdims=True)

array([[1.5185012 ],
       [2.03261402],
       [1.79341946]])

In [23]:
a[range(2), [2, 3]].sum(keepdims = True).shape

(1,)

In [24]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [27]:
x.shape, w.shape, b.shape

((2, 4, 5, 6), (120, 3), (3,))

In [28]:
np.prod(input_shape)

120

In [4]:
np.linspace(0.1, 0.5, num=9)

array([0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ])

In [33]:
i = 2

In [37]:
'W%s' % (i+2)

'W4'

In [41]:
type(4 / 2)

float

In [40]:
type(4 // 2)

int

In [18]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
y = x + np.array([2, 2, 3, 4])

In [19]:
y

array([[ 3,  4,  6,  8],
       [ 7,  8, 10, 12],
       [11, 12, 14, 16]])

In [12]:
y = y + 2

In [13]:
y

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
print(np.version.version)

1.16.3


In [24]:
!pip install numpy==1.16.2

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
     |████████████████████████████████| 13.9MB 756kB/s eta 0:00:01
  Found existing installation: numpy 1.16.3
    Uninstalling numpy-1.16.3:
      Successfully uninstalled numpy-1.16.3


In [25]:
a[:-1]

array([[-1.28626036,  0.10563982, -0.86851349,  1.5185012 , -1.16145324],
       [ 0.5788466 ,  0.78844707,  2.03261402,  1.07951283,  0.08620047]])

In [27]:
a1 = [10] * 3

In [28]:
a1[:-1]

[10, 10]

In [29]:
np.random.randn(3, 4)

array([[ 0.67085158, -0.00478935,  0.23487014,  0.20823826],
       [ 0.18856603, -1.4558452 ,  0.09771323, -0.13150598],
       [ 0.43837888,  1.50511757,  1.58101541,  0.75568119]])

In [31]:
a1=np.random.randint(0,16,2)

In [32]:
a1

array([11,  2])